// apps/mods — メイドさん本体の Mod 実装。最終的な Mod jar はこのモジュールが
// common / modelloader のクラスを取り込んで単一 jar として生成する。
plugins {
    `java-library`
    `maven-publish`
    id("net.neoforged.moddev")
}

val mod_version: String by project
val mod_id: String by project
val minecraft_version: String by project
val minecraft_version_range: String by project
val neo_version: String by project
val mod_name: String by project
val mod_license: String by project

evaluationDependsOn(":apps:common")
evaluationDependsOn(":apps:modelloader")

val commonProject = project(":apps:common")
val modelloaderProject = project(":apps:modelloader")
val commonSourceSets = commonProject.extensions.getByType<SourceSetContainer>()
val modelloaderSourceSets = modelloaderProject.extensions.getByType<SourceSetContainer>()

sourceSets {
    main {
        resources {
            // Include resources generated by data generators.
            srcDir("src/generated/resources")

            // Exclude common development only resources from finalized outputs
            exclude("**/*.bbmodel") // BlockBench project files
            exclude("src/generated/**/.cache") // datagen cache files
        }
    }
}

base {
    archivesName.set(mod_id)
}

// リリース配布用の jar ファイル名: LittleMaidNeo_<Minecraft バージョン>_<Mod バージョン>.jar
tasks.jar {
    archiveFileName.set("${mod_name}_${minecraft_version}_${mod_version}.jar")

    // common / modelloader のクラスを取り込み、単一の Mod jar として配布する
    from(commonSourceSets["main"].output)
    from(modelloaderSourceSets["main"].output)
}

neoForge {
    // Specify the version of NeoForge to use.
    this@neoForge.version = neo_version

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty("forge.logging.markers", "REGISTRIES")

            // Recommended logging level for the console
            logLevel.set(org.slf4j.event.Level.DEBUG)
        }

        create("client") {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty("neoforge.enabledGameTestNamespaces", mod_id)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", mod_id)
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        create("gameTestServer") {
            type.set("gameTestServer")
            systemProperty("neoforge.enabledGameTestNamespaces", mod_id)
        }

        create("clientData") {
            clientData()
            programArguments.addAll("--mod", mod_id, "--all", "--output", file("src/generated/resources/").absolutePath, "--existing", file("src/main/resources/").absolutePath)
        }

        create("serverData") {
            serverData()
            programArguments.addAll("--mod", mod_id, "--all", "--output", file("src/generated/resources/").absolutePath, "--existing", file("src/main/resources/").absolutePath)
        }
    }

    mods {
        // 1 つの Mod (littlemaidneo) を 3 モジュールのソースセットで構成する
        create(mod_id) {
            sourceSet(sourceSets.main.get())
            sourceSet(commonSourceSets["main"])
            sourceSet(modelloaderSourceSets["main"])
        }
    }
}

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
val localRuntime by configurations.creating
configurations {
    runtimeClasspath.get().extendsFrom(localRuntime)
}

dependencies {
    api(project(":apps:modelloader")) // transitively includes :apps:common
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    description = ""
    val replaceProperties = mapOf(
        "minecraft_version" to minecraft_version,
        "minecraft_version_range" to minecraft_version_range,
        "neo_version" to neo_version,
        "mod_id" to mod_id,
        "mod_name" to mod_name,
        "mod_license" to mod_license,
        "mod_version" to mod_version
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.get().resources.srcDir(generateModMetadata)
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask(generateModMetadata)

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("${project.projectDir}/repo")
        }
    }
}

tasks.register<Copy>("mergeData") {
    description = ""
    dependsOn("runClientData", "runServerData")
    from("build/generated/client")
    from("build/generated/server")
    into("src/generated/resources")
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
